spring.application.name=gamelogged
spring.datasource.url=jdbc:postgresql://localhost:5432/game_library
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
rawg.api.key=${RAWG_API_KEY}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.jackson.deserialization.fail-on-unknown-properties=false